/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.eventbus.EventBus
 *  com.google.common.eventbus.Subscribe
 *  net.minecraft.client.Minecraft
 *  net.minecraftforge.common.MinecraftForge
 *  net.minecraftforge.fml.client.FMLFileResourcePack
 *  net.minecraftforge.fml.client.FMLFolderResourcePack
 *  net.minecraftforge.fml.common.DummyModContainer
 *  net.minecraftforge.fml.common.FMLCommonHandler
 *  net.minecraftforge.fml.common.LoadController
 *  net.minecraftforge.fml.common.Loader
 *  net.minecraftforge.fml.common.Mod$EventHandler
 *  net.minecraftforge.fml.common.ModMetadata
 *  net.minecraftforge.fml.common.event.FMLInitializationEvent
 *  net.minecraftforge.fml.common.event.FMLPostInitializationEvent
 *  net.minecraftforge.fml.common.event.FMLPreInitializationEvent
 *  net.minecraftforge.fml.common.event.FMLServerStartingEvent
 *  net.minecraftforge.fml.common.network.NetworkCheckHandler
 *  net.minecraftforge.fml.relauncher.Side
 *  net.minecraftforge.fml.relauncher.SideOnly
 */
package customsteve;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import customsteve.LoadingPlugin;
import customsteve.ModContainer;
import customsteve.aT;
import customsteve.aV;
import customsteve.a_0;
import customsteve.ap_0;
import customsteve.au_0;
import customsteve.aw_0;
import customsteve.ax_0;
import customsteve.ay_0;
import customsteve.b_0;
import customsteve.d;
import customsteve.jni.CS_Bullet;
import customsteve.q;
import customsteve.r;
import customsteve.s_0;
import customsteve.v_0;
import customsteve.x_0;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.Minecraft;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.FMLFileResourcePack;
import net.minecraftforge.fml.client.FMLFolderResourcePack;
import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.network.NetworkCheckHandler;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

/*
 * Duplicate member names - consider using --renamedupmembers true
 */
@SideOnly(value=Side.CLIENT)
public class ModContainer
extends DummyModContainer {
    public static final d a = new d();
    public static final String a = "1.4.0-Beta";
    private static final String c = null;
    public HashMap a = new HashMap();
    public static boolean a = false;
    public static boolean b = true;
    public static a a;
    public static String b;
    public static ModContainer a;
    public static Class<?> a;
    public static Method a;
    public static Method b;
    public static Method c;
    public static Field a;
    public static Field b;

    public ModContainer() {
        super(new ModMetadata());
        ModMetadata meta = this.getMetadata();
        meta.modId = "customsteve";
        meta.name = "CustomSteve";
        meta.description = "CustomSteve is a mod which enables you to change the model of Steve in Minecraft. Which differentiates it from other mods is that it can import models of industry standard into Minecraft\u951b\u5bc3hich may revolutionize the entire Minecraft visual experience!";
        meta.version = a;
        meta.authorList = Arrays.asList("ici2cc", "szszss", "ethernion");
        meta.url = "www.csmod.net";
        meta.logoFile = "logo.jpg";
        meta.autogenerated = false;
        a = this;
        try {
            b = new File(Minecraft.getMinecraft().gameDir, "mods").getCanonicalPath();
        }
        catch (IOException e2) {
            e2.printStackTrace();
        }
    }

    public File getSource() {
        return LoadingPlugin.a;
    }

    public Class<?> getCustomResourcePackClass() {
        return this.getSource().isDirectory() ? FMLFolderResourcePack.class : FMLFileResourcePack.class;
    }

    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register((Object)this);
        return true;
    }

    @Subscribe
    public void preInit(FMLPreInitializationEvent event) {
        b_0.y = Loader.isModLoaded((String)"custombuki");
        if (b_0.y) {
            // empty if block
        }
        this.loadMyConfig();
    }

    @Subscribe
    public void Init(FMLInitializationEvent event) {
        a.a();
        a.a(aT.class);
        a.a(au_0.class);
        a.a(aV.class);
        a.a(aw_0.class);
        a.a(ay_0.class);
        a.a(ax_0.class);
    }

    @Subscribe
    public void postInit(FMLPostInitializationEvent event) {
        a_0.instance = new a_0();
        a_0.instance.a = new CS_Bullet();
        if (b_0.d) {
            b_0.c = true;
            b_0.d = false;
            a_0.instance.a.a();
        }
        if (FMLCommonHandler.instance().getSide() == Side.CLIENT) {
            s_0 kh = new s_0();
            v_0 pa = new v_0();
            MinecraftForge.EVENT_BUS.register((Object)new x_0());
            MinecraftForge.EVENT_BUS.register((Object)new q());
            MinecraftForge.EVENT_BUS.register((Object)new r());
        }
        a.b();
        try {
            b = Class.forName("net.minecraft.client.renderer.RenderGlobal").getDeclaredField("field_147595_R");
            b.setAccessible(true);
            if (LoadingPlugin.a) {
                a = Class.forName("shadersmod.client.Shaders");
                a = ((Class)((Object)a)).getMethod("setCamera", Float.TYPE);
                c = ((Class)((Object)a)).getMethod("setCameraShadow", Float.TYPE);
                b = ((Class)((Object)a)).getMethod("endHand", new Class[0]);
                a = ((Class)((Object)a)).getField("isShaderPackInitialized");
            }
        }
        catch (Exception e2) {
            e2.printStackTrace();
        }
    }

    public boolean isShaderPackInitialized() {
        try {
            return a.getBoolean(null);
        }
        catch (IllegalArgumentException e2) {
            e2.printStackTrace();
        }
        catch (IllegalAccessException e3) {
            e3.printStackTrace();
        }
        return false;
    }

    public void shadersModSetCamera(float f2) {
        try {
            a.invoke(null, Float.valueOf(f2));
        }
        catch (IllegalAccessException e2) {
            e2.printStackTrace();
        }
        catch (IllegalArgumentException e3) {
            e3.printStackTrace();
        }
        catch (InvocationTargetException e4) {
            e4.printStackTrace();
        }
    }

    public void shadersModSetCameraShadow(float f2) {
        try {
            c.invoke(null, Float.valueOf(f2));
        }
        catch (IllegalAccessException e2) {
            e2.printStackTrace();
        }
        catch (IllegalArgumentException e3) {
            e3.printStackTrace();
        }
        catch (InvocationTargetException e4) {
            e4.printStackTrace();
        }
    }

    @Subscribe
    public void serverStart(FMLServerStartingEvent event) {
    }

    public void loadMyConfig() {
        a = new a(this);
        ModContainer.a.c = Minecraft.getMinecraft().getSession().getUsername();
        File path = new File(b + "/" + "CustomSteve/models");
        if (!path.exists()) {
            path.mkdirs();
        }
        if (!(path = new File(b + "/" + "CustomSteve/Animations")).exists()) {
            path.mkdirs();
        }
        try {
            File file = new File(b + "/" + "CustomSteve/CS.txt");
            if (!file.exists()) {
                this.saveMyConfig();
            }
            InputStreamReader read = new InputStreamReader(new FileInputStream(file));
            BufferedReader bufferedReader = new BufferedReader(read);
            String lineTxt = null;
            while ((lineTxt = bufferedReader.readLine()) != null) {
                String[] s;
                String status;
                if (lineTxt.indexOf("textures:") != -1) {
                    ModContainer.a.a = lineTxt.replace("textures:", "");
                    continue;
                }
                if (lineTxt.indexOf("model:") != -1) {
                    ModContainer.a.b = lineTxt.replace("model:", "");
                    continue;
                }
                if (lineTxt.indexOf("BGM:") != -1) {
                    b_0.b = lineTxt.replace("BGM:", "");
                    continue;
                }
                if (lineTxt.indexOf("enable:") != -1) {
                    status = lineTxt.replace("enable:", "");
                    if (status.equals("on")) {
                        b_0.m = true;
                        continue;
                    }
                    b_0.m = false;
                    continue;
                }
                if (lineTxt.indexOf("physics:") != -1) {
                    status = lineTxt.replace("physics:", "");
                    if (status.equals("on") && CS_Bullet.a) {
                        b_0.d = true;
                        continue;
                    }
                    b_0.d = false;
                    continue;
                }
                if (lineTxt.indexOf("autoreload:") != -1) {
                    status = lineTxt.replace("autoreload:", "");
                    if (status.equals("on") && b_0.d) {
                        b_0.e = true;
                        continue;
                    }
                    b_0.e = false;
                    continue;
                }
                if (lineTxt.indexOf("hardCALC:") != -1) {
                    status = lineTxt.replace("hardCALC:", "");
                    if (status.equals("on")) {
                        b_0.f = false;
                        continue;
                    }
                    b_0.f = true;
                    continue;
                }
                if (lineTxt.indexOf("drawFirstPerson:") != -1) {
                    status = lineTxt.replace("drawFirstPerson:", "");
                    if (status.equals("on")) {
                        b_0.r = true;
                        continue;
                    }
                    b_0.r = false;
                    continue;
                }
                if (lineTxt.indexOf("autoSwitch:") != -1) {
                    status = lineTxt.replace("autoSwitch:", "");
                    b_0.a = Integer.parseInt(status);
                    continue;
                }
                if (lineTxt.indexOf("speed:") != -1) {
                    status = lineTxt.replace("speed:", "");
                    b_0.a = Float.parseFloat(status);
                    continue;
                }
                if (lineTxt.indexOf("cameraRotation:") != -1) {
                    String rot = lineTxt.replace("cameraRotation:", "");
                    b_0.h = Float.parseFloat(rot);
                    continue;
                }
                if (lineTxt.indexOf("cameraDistance:") != -1) {
                    String dis = lineTxt.replace("cameraDistance:", "");
                    b_0.e = Float.parseFloat(dis);
                    continue;
                }
                if (lineTxt.indexOf("size:") == -1 || (s = (status = lineTxt.replace("size:", "")).split(","))[0] == null || s[0].equals("")) continue;
                if (s.length > 2 && s[1] != null && s[2] != null && !s[1].equals("") && s[2] != null && !s[2].equals("")) {
                    b_0.b = new ap_0(Float.parseFloat(s[0]), Float.parseFloat(s[1]), Float.parseFloat(s[2]));
                    continue;
                }
                b_0.b = new ap_0(Float.parseFloat(s[0]), Float.parseFloat(s[0]), Float.parseFloat(s[0]));
            }
            b_0.f = false;
            read.close();
        }
        catch (Exception e2) {
            System.out.println("[CustomSteve]Failed to load config file\n" + e2.getMessage());
            e2.printStackTrace();
        }
    }

    public void saveMyConfig() {
        try {
            File file = new File(b + "/" + "CustomSteve/CS.txt");
            if (file.exists()) {
                file.delete();
            }
            if (!file.createNewFile()) {
                throw new IOException("[CustomSteve]Failed to re-create config file.");
            }
            OutputStreamWriter writer = new OutputStreamWriter(new FileOutputStream(file));
            BufferedWriter bufferedWriter = new BufferedWriter(writer);
            bufferedWriter.write("textures:");
            bufferedWriter.write(ModContainer.a.a);
            bufferedWriter.newLine();
            bufferedWriter.write("model:");
            bufferedWriter.write(ModContainer.a.b);
            bufferedWriter.newLine();
            bufferedWriter.write("BGM:");
            bufferedWriter.write(b_0.b);
            bufferedWriter.newLine();
            bufferedWriter.write("enable:");
            bufferedWriter.write(b_0.m ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("physics:");
            bufferedWriter.write(b_0.c ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("autoreload:");
            bufferedWriter.write(b_0.e ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("hardCALC:");
            bufferedWriter.write(!b_0.f ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("drawFirstPerson:");
            bufferedWriter.write(b_0.r ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("autoSwitch:");
            bufferedWriter.write(b_0.a + "");
            bufferedWriter.newLine();
            bufferedWriter.write("cameraRotation:");
            bufferedWriter.write(b_0.h + "");
            bufferedWriter.newLine();
            bufferedWriter.write("cameraDistance:");
            bufferedWriter.write(b_0.e + "");
            bufferedWriter.flush();
            bufferedWriter.close();
            writer.close();
        }
        catch (Exception e2) {
            System.out.println("[CustomSteve]Failed to load config file");
            e2.printStackTrace();
        }
    }

    public String getModId() {
        return "customsteve";
    }

    @NetworkCheckHandler
    public boolean checker(Map<String, String> versions, Side side) {
        return true;
    }

    @Mod.EventHandler
    public void onServerStarting(FMLServerStartingEvent ev) {
    }

    public void p(Object s) {
    }

    static {
        a = null;
        a = null;
        b = null;
        c = null;
        a = null;
        b = null;
    }
}

