/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.eventbus.EventBus
 *  com.google.common.eventbus.Subscribe
 *  cpw.mods.fml.client.FMLFileResourcePack
 *  cpw.mods.fml.client.FMLFolderResourcePack
 *  cpw.mods.fml.common.DummyModContainer
 *  cpw.mods.fml.common.FMLCommonHandler
 *  cpw.mods.fml.common.LoadController
 *  cpw.mods.fml.common.Loader
 *  cpw.mods.fml.common.Mod$EventHandler
 *  cpw.mods.fml.common.ModMetadata
 *  cpw.mods.fml.common.event.FMLInitializationEvent
 *  cpw.mods.fml.common.event.FMLPostInitializationEvent
 *  cpw.mods.fml.common.event.FMLPreInitializationEvent
 *  cpw.mods.fml.common.event.FMLServerStartingEvent
 *  cpw.mods.fml.common.network.NetworkCheckHandler
 *  cpw.mods.fml.relauncher.Side
 *  cpw.mods.fml.relauncher.SideOnly
 *  custombuki.CustomBukiMod
 *  net.minecraft.client.Minecraft
 *  net.minecraftforge.common.MinecraftForge
 */
import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import cpw.mods.fml.client.FMLFileResourcePack;
import cpw.mods.fml.client.FMLFolderResourcePack;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.network.NetworkCheckHandler;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import custombuki.CustomBukiMod;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.Minecraft;
import net.minecraftforge.common.MinecraftForge;

@SideOnly(value=Side.CLIENT)
public class ModContainer
extends DummyModContainer {
    public static final PacketPipelineClient array$ = new PacketPipelineClient();
    public static final String enhanced$ = "1.4.1-Beta";
    private static final String themes$ = null;
    public HashMap process$ = new HashMap();
    public static boolean bored$ = false;
    public static boolean segments$ = true;
    public static ModContainer2 dealing$;
    public static String outreach$;
    public static ModContainer athletes$;
    public static Class chains$;
    public static Method gives$;
    public static Method assumed$;
    public static Method bother$;
    public static Field alive$;
    public static Field mating$;

    public ModContainer() {
        super(new ModMetadata());
        ModMetadata meta = this.getMetadata();
        meta.modId = "customsteve";
        meta.name = "CustomSteve";
        meta.description = "CustomSteve is a mod which enables you to change the model of Steve in Minecraft. Which differentiates it from other mods is that it can import models of industry standard into Minecraft\uff0cwhich may revolutionize the entire Minecraft visual experience!";
        meta.version = enhanced$;
        meta.authorList = Arrays.asList("ici2cc", "szszss", "ethernion");
        meta.url = "www.csmod.net";
        meta.logoFile = "logo.jpg";
        meta.autogenerated = false;
        athletes$ = this;
        try {
            outreach$ = new File(Minecraft.func_71410_x().field_71412_D, "mods").getCanonicalPath();
        }
        catch (IOException e2) {
            e2.printStackTrace();
        }
    }

    public File getSource() {
        return LoadingPlugin.protest$;
    }

    public Class getCustomResourcePackClass() {
        return this.getSource().isDirectory() ? FMLFolderResourcePack.class : FMLFileResourcePack.class;
    }

    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register((Object)this);
        return true;
    }

    @Subscribe
    public void preInit(FMLPreInitializationEvent event) {
        Config.permit$ = Loader.isModLoaded((String)"custombuki");
        if (Config.permit$) {
            event.getModMetadata().childMods.add(CustomBukiMod.a);
        }
        this.loadMyConfig();
    }

    @Subscribe
    public void Init(FMLInitializationEvent event) {
        array$.a();
        array$.a(P000_Login.class);
        array$.a(P100_ModelInfomation.class);
        array$.a(P200_ModelInfomationUpdate2.class);
        array$.a(P201_AnimationStatus.class);
        array$.a(P400_Error.class);
        array$.a(P202_PlayerInfomationUpdate.class);
    }

    @Subscribe
    public void postInit(FMLPostInitializationEvent event) {
        CSmanager.cellular$ = new CSmanager();
        CSmanager.cellular$.december$ = new CS_Bullet();
        if (Config.globe$) {
            Config.point$ = true;
            Config.globe$ = false;
            CSmanager.cellular$.december$._savings();
        }
        if (FMLCommonHandler.instance().getSide() == Side.CLIENT) {
            KeyHandler kh = new KeyHandler();
            NetWorkHandler pa = new NetWorkHandler();
            FMLCommonHandler.instance().bus().register((Object)new PlayerUpdateTickHandler());
            MinecraftForge.EVENT_BUS.register((Object)new GuiEvent());
        }
        array$.b();
        if (LoadingPlugin.agencies$) {
            try {
                chains$ = Class.forName("shadersmod.client.Shaders");
                gives$ = chains$.getMethod("setCamera", Float.TYPE);
                bother$ = chains$.getMethod("setCameraShadow", Float.TYPE);
                assumed$ = chains$.getMethod("endHand", new Class[0]);
                alive$ = chains$.getField("isShaderPackInitialized");
            }
            catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }

    @Subscribe
    public void serverStart(FMLServerStartingEvent event) {
    }

    public void loadMyConfig() {
        dealing$ = new ModContainer2(this);
        ModContainer.dealing$.highways$ = Minecraft.func_71410_x().func_110432_I().func_111285_a();
        File path = new File(outreach$ + "/" + "CustomSteve/models");
        if (!path.exists()) {
            path.mkdirs();
        }
        if (!(path = new File(outreach$ + "/" + "CustomSteve/Animations")).exists()) {
            path.mkdirs();
        }
        try {
            File file = new File(outreach$ + "/" + "CustomSteve/CS.txt");
            if (!file.exists()) {
                this.saveMyConfig();
            }
            InputStreamReader read = new InputStreamReader(new FileInputStream(file));
            BufferedReader bufferedReader = new BufferedReader(read);
            String lineTxt = null;
            while ((lineTxt = bufferedReader.readLine()) != null) {
                String[] s;
                String status;
                if (lineTxt.indexOf("textures:") != -1) {
                    ModContainer.dealing$.method$ = lineTxt.replace("textures:", "");
                    continue;
                }
                if (lineTxt.indexOf("model:") != -1) {
                    ModContainer.dealing$.talking$ = lineTxt.replace("model:", "");
                    continue;
                }
                if (lineTxt.indexOf("BGM:") != -1) {
                    Config.gadgets$ = lineTxt.replace("BGM:", "");
                    continue;
                }
                if (lineTxt.indexOf("enable:") != -1) {
                    status = lineTxt.replace("enable:", "");
                    if (status.equals("on")) {
                        Config.scored$ = true;
                        continue;
                    }
                    Config.scored$ = false;
                    continue;
                }
                if (lineTxt.indexOf("physics:") != -1) {
                    status = lineTxt.replace("physics:", "");
                    if (status.equals("on") && CS_Bullet.income$) {
                        Config.globe$ = true;
                        continue;
                    }
                    Config.globe$ = false;
                    continue;
                }
                if (lineTxt.indexOf("autoreload:") != -1) {
                    status = lineTxt.replace("autoreload:", "");
                    if (status.equals("on") && Config.globe$) {
                        Config.leaves$ = true;
                        continue;
                    }
                    Config.leaves$ = false;
                    continue;
                }
                if (lineTxt.indexOf("hardCALC:") != -1) {
                    status = lineTxt.replace("hardCALC:", "");
                    if (status.equals("on")) {
                        Config.maybe$ = false;
                        continue;
                    }
                    Config.maybe$ = true;
                    continue;
                }
                if (lineTxt.indexOf("drawFirstPerson:") != -1) {
                    status = lineTxt.replace("drawFirstPerson:", "");
                    if (status.equals("on")) {
                        Config.baghdad$ = true;
                        continue;
                    }
                    Config.baghdad$ = false;
                    continue;
                }
                if (lineTxt.indexOf("autoSwitch:") != -1) {
                    status = lineTxt.replace("autoSwitch:", "");
                    Config.price$ = Integer.parseInt(status);
                    continue;
                }
                if (lineTxt.indexOf("speed:") != -1) {
                    status = lineTxt.replace("speed:", "");
                    Config.celebs$ = Float.parseFloat(status);
                    continue;
                }
                if (lineTxt.indexOf("cameraRotation:") != -1) {
                    String rot = lineTxt.replace("cameraRotation:", "");
                    Config.aurora$ = Float.parseFloat(rot);
                    continue;
                }
                if (lineTxt.indexOf("cameraDistance:") != -1) {
                    String dis = lineTxt.replace("cameraDistance:", "");
                    Config.tests$ = Float.parseFloat(dis);
                    continue;
                }
                if (lineTxt.indexOf("size:") == -1 || (s = (status = lineTxt.replace("size:", "")).split(","))[0] == null || s[0].equals("")) continue;
                if (s.length > 2 && s[1] != null && s[2] != null && !s[1].equals("") && s[2] != null && !s[2].equals("")) {
                    Config.child$ = new Vector3f(Float.parseFloat(s[0]), Float.parseFloat(s[1]), Float.parseFloat(s[2]));
                    continue;
                }
                Config.child$ = new Vector3f(Float.parseFloat(s[0]), Float.parseFloat(s[0]), Float.parseFloat(s[0]));
            }
            Config.maybe$ = false;
            read.close();
        }
        catch (Exception e2) {
            System.out.println("[CustomSteve]Failed to load config file\n" + e2.getMessage());
            e2.printStackTrace();
        }
    }

    public void saveMyConfig() {
        try {
            File file = new File(outreach$ + "/" + "CustomSteve/CS.txt");
            if (file.exists()) {
                file.delete();
            }
            if (!file.createNewFile()) {
                throw new IOException("[CustomSteve]Failed to re-create config file.");
            }
            OutputStreamWriter writer = new OutputStreamWriter(new FileOutputStream(file));
            BufferedWriter bufferedWriter = new BufferedWriter(writer);
            bufferedWriter.write("textures:");
            bufferedWriter.write(ModContainer.dealing$.method$);
            bufferedWriter.newLine();
            bufferedWriter.write("model:");
            bufferedWriter.write(ModContainer.dealing$.talking$);
            bufferedWriter.newLine();
            bufferedWriter.write("BGM:");
            bufferedWriter.write(Config.gadgets$);
            bufferedWriter.newLine();
            bufferedWriter.write("enable:");
            bufferedWriter.write(Config.scored$ ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("physics:");
            bufferedWriter.write(Config.point$ ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("autoreload:");
            bufferedWriter.write(Config.leaves$ ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("hardCALC:");
            bufferedWriter.write(!Config.maybe$ ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("drawFirstPerson:");
            bufferedWriter.write(Config.baghdad$ ? "on" : "off");
            bufferedWriter.newLine();
            bufferedWriter.write("autoSwitch:");
            bufferedWriter.write(Config.price$ + "");
            bufferedWriter.newLine();
            bufferedWriter.write("cameraRotation:");
            bufferedWriter.write(Config.aurora$ + "");
            bufferedWriter.newLine();
            bufferedWriter.write("cameraDistance:");
            bufferedWriter.write(Config.tests$ + "");
            bufferedWriter.flush();
            bufferedWriter.close();
            writer.close();
        }
        catch (Exception e2) {
            System.out.println("[CustomSteve]Failed to load config file");
            e2.printStackTrace();
        }
    }

    public String getModId() {
        return "customsteve";
    }

    @NetworkCheckHandler
    public boolean checker(Map versions, Side side) {
        return true;
    }

    @Mod.EventHandler
    public void onServerStarting(FMLServerStartingEvent ev2) {
    }

    public void p(Object s) {
    }

    static {
        chains$ = null;
        gives$ = null;
        assumed$ = null;
        bother$ = null;
        alive$ = null;
        mating$ = null;
    }
}

